#!groovy

// Generated by IBM TransformationAdvisor
// Sun Jul 07 13:49:11 IST 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'tangoappwar'
    mvnCommands = '--version'
    test='false'
}